### ISSUE TITLE
Öneriler

### ISSUE THREAD

**Issue by mertcenikut** [gurkanuzunca/newsbull#24]
Merhabalar,

Bu Script'ye AMP desteği ve Google, Yandex News sitemapı eklense ücretli scriptlerin hepsinden daha çok kullanılır :)

Sevgiler, Saygılar.

**Comment by gurkanuzunca** [comment]
Selamlar,
Google news sitemapi şuanda sistemde bulunmakta. Yandex news de aynı sitemapi destekliyorsa yandex için de bir sorun olmayacaktır diye düşünüyorum.
AMP desteği konusunda mobil kısma ağırlık verdiğimizde amp ile alakalı da güncellemeler yapacağız.

**Comment by gurkanuzunca** [comment]
#26 Amp desteği yeni günellemede yapılacak.
